Added transition on testimonial cards.
ALPHAVIO/WordNook pull request #1004
Opened 2021-06-10 08:10 UTC by supzi-del

## What is the change?
Added a transition duration of 0.5s when hovered upon testimonial card divs.

## Related issue?
close: #1000 

## How was it tested?

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Did you lint your code before making the Pull Request?
- [] Have you made corresponding changes to the documentation?
- [] Your submission doesn't break any existing feature.
- [] Have you tested the code before submission?

2021-06-10 17:16 UTC, Ayush0730 approved these changes

2021-06-11 00:15 UTC, Pranav016 requested changes
- Usually I'd advice adding a screenshot or a screen-recording(in this case) to the PR description to show that the changes actually work.
- Make PR from a new branch instead of master

2021-06-11 00:15 UTC, Pranav016 commented on public/css/styles.css
> +	transition: all 0.5s;
Isn't the animation on hover so I don't think adding `transition` property to a div would affect that.

2021-06-11 07:06 UTC, supzi-del commented on public/css/styles.css
> +	transition: all 0.5s;
I have tested it and only then made a PR. Please can you check the screen recording I have updated?

2021-06-11 07:10 UTC, supzi-del commented on public/css/styles.css
> +	transition: all 0.5s;
Should I make a PR to the "deploy" branch?

2021-06-11 07:14 UTC, Pranav016 commented on public/css/styles.css
> +	transition: all 0.5s;
> Should I make a PR to the "deploy" branch?

Next time you can make PR from a new branch to master of ALPHAVIO/WordNook. Just a good practice.

2021-06-11 07:15 UTC, merged