Testimonial made Persistant
ALPHAVIO/WordNook pull request #1022
Opened 2021-06-21 13:14 UTC by YOGESH256

## What is the change?
I have added a testimonial schema in models folder exported it to the testimonial-router.js .As there were some predefined 
testimonials . I have contributed in such a way that new testimonial by a logged in user will be added in addition to predefined rendering of the testimonial. 

## Related issue?
close: #985 

## How was it tested?
it was Tested locally

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

2021-06-21 13:34 UTC, YOGESH256 commented
I have made this contribution under the program LGM-SOC . please review it.

2021-06-21 14:31 UTC, Pranav016 requested changes
Good work, clean code.
Few changes required, write good commit messages to keep commit history clean 👍

2021-06-21 14:31 UTC, Pranav016 commented on routes/testimonial.router.js
>  });
Use try-catch in this controller to handle any error in saving the testimonial to the database.

2021-06-21 14:31 UTC, Pranav016 commented on package.json
>  		"pac-resolver": "^4.2.0"
Revert your last commit where you have updated the dependencies, our dependencies are updated by our bot after checking if they are compatible. Please refrain from making any changes to `package.json` or `package-lock.json` files.

2021-06-21 14:31 UTC, Pranav016 commented on routes/testimonial.router.js
> +
This could be a costly operation, we could send the ones received from the database along with the dummy testimonials and render it below them. Not sure but this definitely is the easier method. I'd like to hear reviews of other mentors on this. @Ayush0730 @theBeginner86

2021-06-21 14:51 UTC, YOGESH256 commented on routes/testimonial.router.js
>  });
Yeah I will do it

2021-06-21 14:52 UTC, YOGESH256 commented on routes/testimonial.router.js
> +
Sure!

2021-06-21 15:10 UTC, YOGESH256 commented on package.json
>  		"pac-resolver": "^4.2.0"
Reverted! and Noted!

2021-06-21 17:14 UTC, theBeginner86 commented on routes/testimonial.router.js
> +
Yeah, even I am thinking like that. 
Though this method is easier to implement (considering the amount of new code to be written), at the same time it is costly in the sense that we using two forms of DB for storing the same kind of data. 

See even if we try to render the data from both the DB separately (i.e, array and the MongoDB) then though we could save some time of copying the new testimonials from MongoDB to testimonials array but that time would be compensated in traversing through the testimonials and printing them separately from MongoDB and the array.

The only way I can think of to reduce the time would be to use either an array or MongoDB. According to good practice, we should be going with MongoDB. So, we need to try to solve this in some effective way by using just MongoDB.

Right now the code works fine so we can merge this one but we could raise a new issue for seeing if some contributor could come up with some innovative idea to solve this.

Let me know how this sounds.

2021-06-21 17:16 UTC, Pranav016 commented on routes/testimonial.router.js
> +
Sounds good, even I think that for now this is the easiest way we can get it done.

2021-06-21 18:34 UTC, Pranav016 requested changes
- There are a lot of changes your package-lock file mainly due to difference in versions, check README for instructions to update your package-lock file version. We don't accept PRs with changes to package-lock file so please revert them. When you upgrade lock file version and make PR it will get fixed automatically.
- Use try catch block for error handling while saving data to database.

2021-06-22 08:02 UTC, YOGESH256 commented
@Pranav016  I think I have made a huge blunder as you I have made changes  to the array in the get request itself 
so if i refresh the page the testimonials will be added again in the array. so as @theBeginner86  said that have to use mongodb  as it will be better. so why not change the view itself as seen in the above code as follows. 


![testimonail-write-js](https://user-images.githubusercontent.com/67831090/122886703-cfffd000-d35d-11eb-8560-444baff58695.PNG)
![testimonial-router js](https://user-images.githubusercontent.com/67831090/122886749-daba6500-d35d-11eb-82ca-90ac8965bc66.PNG)


In the above code predefined  testimonials are added as well as the testimonials from the database. What do you think of this approach. Sorry for the blunder I made. Pls tell me your suggestions on the above approach

2021-06-22 08:12 UTC, Pranav016 commented
> @Pranav016 I think I have made a huge blunder as you I have made changes to the array in the get request itself
> so if i refresh the page the testimonials will be added again in the array. so as @theBeginner86 said that have to use mongodb as it will be better. so why not change the view itself as seen in the above code as follows.
> 
> ![testimonail-write-js](https://user-images.githubusercontent.com/67831090/122886703-cfffd000-d35d-11eb-8560-444baff58695.PNG)
> ![testimonial-router js](https://user-images.githubusercontent.com/67831090/122886749-daba6500-d35d-11eb-82ca-90ac8965bc66.PNG)
> 
> In the above code predefined testimonials are added as well as the testimonials from the database. What do you think of this approach. Sorry for the blunder I made. Pls tell me your suggestions on the above approach

Yup, that's what I was worried about in the first place but now let's do this approach of rendering testimonials from database after predefined ones. You can raise a new issue for this and make PR then.

2021-06-22 08:26 UTC, YOGESH256 commented
ok then  I will a new issue then.

2021-06-22 19:00 UTC, Pranav016 commented
> ok then I will a new issue then or Should I make a pull request again on the same issue as the aim of the issue is almost same

My bad, make PR under #985  only

2021-06-22 19:42 UTC, closed without merging