fetched testimonials from the DB
ALPHAVIO/WordNook pull request #1029
Opened 2021-06-22 19:35 UTC by YOGESH256

## What is the change?
I have added a testimonial schema in models folder exported it to the testimonial-router.js .As there were some predefined
testimonials . I have contributed in such a way that new testimonial by a logged in user will be added in addition to predefined rendering of the testimonial.

## Related issue?
close: #985 

## How was it tested?
It was tested locally.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

2021-06-22 19:37 UTC, YOGESH256 commented
I have made the necesscary changes . Pls review it accordingly. also contributing as a LGM-SOC participant

2021-06-23 09:04 UTC, theBeginner86 requested changes
Good Work 👍
Rest everything is working fine. I did run your code and was able to store the testimonials.

Also, next time if you could add a demo video then that would be great.🙂

2021-06-23 09:04 UTC, theBeginner86 commented on routes/testimonial.router.js
> +		}
- See, as you are not using the com variable value so don't store the return status of the save()
 - Now, instead of this make use of try...catch block. This is in accordance with the good practice of always using try...catch block for storing data in the DB.
 
#### You can take reference from the following snippet:

``` 

try {
		await newtestimonial.save();
	} catch (e) {
		console.log(e);
		return res.redirect('/error');
	}

```

Though, I would also recommend you to read more about try and catch from here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch

2021-06-23 11:02 UTC, YOGESH256 commented on routes/testimonial.router.js
> +		}
Thanks for the advice.  I have written the following code  and if some thing happens like could not able to save the data or 
or in some case I intentionally written the wrong code so the 404 page appears .  below the pic  is the actual code. 
Pls verify it .

![could not save dta](https://user-images.githubusercontent.com/67831090/123083776-09a80800-d43e-11eb-9e4f-9aab1c1b1161.PNG)

` 
// Get request for testimonial-wall
router.get('/testimonial-wall', auth, async (req, res) => {
	const testimonial = await Testimonial.find();

	res.render('./testimonials/testimonial-wall', {
		isAuthenticated: !!req.user,
		testimonials,
		testimonial,
	});
});

// Post request for testimonial-wall
router.post('/testimonial-wall', auth, async (req, res) => {
	const inputViews = req.body.views;
	const _id = req.user;
	const user = await User.findById(_id);
	const inputAuthor = `${user.firstName} ${user.lastName}`;
	// Adding a new Testimonial in the database
	const newtestimonial = new Testimonial({
		author: inputAuthor,
		views: inputViews,
	});

	try{
	 await newtestimonial.sve();
   } catch(e)
  {
	 console.log(e);
	 return res.redirect('/error');
 }
	res.redirect('/testimonial-wall');
});


router.get('/error' ,auth, async (req, res) => {

res.render('./404' , {isAuthenticated: !!req.user});

} )


Should I make some more changes or push it ? 


`
	  `

2021-06-24 14:05 UTC, theBeginner86 commented on routes/testimonial.router.js
> +		}
See everything else was fine. Don't add/edit too many things which are not required or could make the documentation of the code difficult to be read and understand by other contributors.
BTW that error page code router that you added is not required here. 🙂
If you could just do the changes that I have asked then that would be more than enough for this PR to be merged succesfully. 👍

2021-06-24 14:23 UTC, theBeginner86 commented on routes/testimonial.router.js
> +		}
No problem that is totally fine to ask doubts.
Moreover the code snippet, I shared in that we are console loging as well as redirecting.

Have a look at it again. 👍
https://github.com/ALPHAVIO/WordNook/pull/1029#discussion_r656902319

2021-06-24 14:24 UTC, YOGESH256 commented on routes/testimonial.router.js
> +		}
where to redirect ?

2021-06-24 14:33 UTC, theBeginner86 commented on routes/testimonial.router.js
> +		}
to '/error' route. We have already set that up.

2021-06-24 15:08 UTC, YOGESH256 commented on routes/testimonial.router.js
> +		}
I have removed the extra router part and made the changes you told me too.  I hope this is Good!

2021-06-24 15:14 UTC, theBeginner86 approved these changes
Good work 👍
Thanks for the quick fix.

2021-06-24 16:59 UTC, merged