Added missing "?"
ALPHAVIO/WordNook pull request #1037
Opened 2021-06-29 11:43 UTC by supzi-del

## What is the change?
Added "?" in "looking for something" on homepage

## Related issue?
close: #1033 

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Did you lint your code before making the Pull Request?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

2021-06-29 18:12 UTC, theBeginner86 requested changes
Please add a screenshot of the changes made. This would help us in reviewing your PR more effectively.
I know you have just added a 'question mark' but still, please try to follow the PR template.

2021-06-30 11:34 UTC, theBeginner86 commented on views/navitems/home.ejs
> +            <h3 class="normal-heading-font fweight-600">Looking for something?....</h3>
It looks good. 👍
But I would suggest you to remove the '...' if you'd like to add '?'. 
Because keeping both a '?' and '....' looks like we are repeating the same thing.

2021-06-30 17:29 UTC, supzi-del commented on views/navitems/home.ejs
> +            <h3 class="normal-heading-font fweight-600">Looking for something?....</h3>
Yeah, that's right. I've made the changes.

2021-07-01 07:46 UTC, theBeginner86 approved these changes
Looks good👍
@supzi-del please be specific with the commit messages. The commit messages which you used are a bit vague. Usually, the commit message should always contain the description of the changes made with the name of the file in which changes are done.
So, for your case, it could be `improved heading on homepage`
You may take reference from this: https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/

From next time, we won't accept such PRs with vague commit messages. 
I hope you are taking it constructively. I am just giving a bit of honest advice. 🙂

2021-07-01 07:58 UTC, merged