Added Developer Days to Program Section in Readme
ALPHAVIO/WordNook pull request #1104
Opened 2021-09-06 17:36 UTC by saloni-15

## What is the change?
Just added developer days in the Program Section of Readme

## Related issue?
close: #1103

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Did you lint your code before making the Pull Request?
- [] Have you made corresponding changes to the documentation?
- [] Your submission doesn't break any existing feature.
- [] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.
![Capture](https://user-images.githubusercontent.com/75828760/132249507-d93974b2-7ce0-4526-bf49-3b83e11696db.PNG)

2021-09-06 19:55 UTC, Pranav016 requested changes

2021-09-06 19:55 UTC, Pranav016 commented on README.md
> +- It is a 5-week long event. It consists of three tracks that are Web Development, Android Development, and UI/UX Design. The event consists of various sessions and challenges. Various swags and priz
* Remove the swags line, we try to avoid promoting contributing to open-source in exchange for swags/ prizes.

* Add some context-
`It is a 5-week long event.`

2021-09-07 02:58 UTC, saloni-15 commented
![Capture2](https://user-images.githubusercontent.com/75828760/132277270-08d7a4c5-4a27-4e7a-a67c-69ebc9d5f5e0.PNG)

Please review.

2021-09-07 07:42 UTC, Pranav016 approved these changes

2021-09-07 07:42 UTC, merged