testimonial added
ALPHAVIO/WordNook pull request #704
Opened 2021-04-18 16:45 UTC by Ankita297

## What is the change?
Testimonial section added .
## Related issue?
close: #342 

## How was it tested?
I have tested it in my local system .
## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

https://user-images.githubusercontent.com/67833077/115153432-7b0cb880-a093-11eb-8efd-23ed197886dd.mp4

2021-04-18 17:01 UTC, Ankita297 commented
@Pranav016  Please review my PR . Why the test is failing ?
I have added the frontend part and schema . I was not able to create routing of testimonial to home page .

2021-04-18 18:17 UTC, Pranav016 requested changes
Changes look fine, a couple things
* you can place testimonial page's css above footer's css so its easier to index
* you can make a new router for testimonial since the index router is getting pretty long and cluttered up.
Just some small things otherwise it looks good.

Also I didn't get your query about not able to redirect to home? can you elaborate ?
I know it wouldn't be an issue in redirection(since that's easy for you) but some other thing, let me know

2021-04-18 18:17 UTC, Pranav016 commented on views/partials/footer.ejs
> +<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
latest bootstrap and jquery are already present I think, so are these required ?
Might make the site slow if there are a lot of scripts required to be loaded

2021-04-18 18:26 UTC, Ankita297 commented
@Pranav016 I am not able to render the testimonial  to home page  .
As when somebody add the testimonial then it should reflect on home page .
I am not to add dynamically ejs part .

2021-04-18 19:42 UTC, Pranav016 commented
> @Pranav016 I am not able to render the testimonial to home page .
> As when somebody add the testimonial then it should reflect on home page .
> I am not to add dynamically ejs part .

I think one solution to that could be
* we only display 3-4 testimonials on the home page carousel but there is a testimonials wall/ page where any new testimonial added will be displayed.

Even though its not hard to update/ add the testimonials in the carousel( I think you implemented a carousel right?) but having 100 testimonials in a carousel doesn't make sense, 3-4 are fine..

Also can you add another demo video if possible because I couldn't see the carousel correctly in this video ^
might be some changes required in that too..

2021-04-19 01:54 UTC, Ankita297 commented
Okay @Pranav016  I will do that .

2021-04-19 19:42 UTC, Pranav016 commented
> Okay @Pranav016 I will do that .

For this PR just add a 3-4 testimonials for the website on a carousel on the home page. Then someone else can implement the actual testimonials page..
So for this PR you can remove the GET requests etc that you've added for the testimonials page and leave it to be solved in another issue..

2021-04-20 08:24 UTC, Ankita297 commented
@Pranav016  First  I have created a testimonial section . There is button of add a testimonial . If the user click on it , It will first check if user is authenticated or not . If not then it will be redirected to log in page . Otherwise it will open Write the testimonial page .
There is a form which has input for views of user . I have done it till this .

So basically other person has to create a schema and save the data in database the render it on home page .
You can use a for loop which will render last  testimonials .

2021-04-20 08:32 UTC, Ankita297 commented
![Daily Journal - Google Chrome 20-04-2021 13_54_04](https://user-images.githubusercontent.com/67833077/115364338-eb752000-a1e0-11eb-9a88-0820b08251e7.png)
![Daily Journal - Google Chrome 20-04-2021 13_55_39](https://user-images.githubusercontent.com/67833077/115364387-f92aa580-a1e0-11eb-96f0-52207606f439.png)

2021-04-20 08:33 UTC, Ankita297 commented
@Pranav016  is it okay now or need some changes .

2021-04-20 18:39 UTC, Pranav016 requested changes

2021-04-20 18:39 UTC, Pranav016 commented on public/css/styles.css
> +    margin-top:-5px;
Most of the values here are hard coded in `px`, convert to relative units such as `rem em % vh vw` to maintain responsiveness

2021-04-20 18:39 UTC, Pranav016 commented on views/partials/footer.ejs
> +<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
Please reply to this

2021-04-20 18:39 UTC, Pranav016 commented on views/partials/testimonial.ejs
> +                        </div>
Take advantage of using an ejs file and use JavaScript to do the work. You have hard coded all the data as html which is not ideal.

Put the data in another file as javascript object and send it in the get request.
then make use of the fact that you can use javascript here and use loop in the file to display all the data. example-
```
<% posts.forEach(function (post) { %>
        <div class="post-preview col-lg-5 mx-2 mx-md-auto py-3 my-3">
            <div class="my-1">
                <a href="/author/<%= post.author._id %> " class="mb-4 fw-bold f-size-22px">
                    <i class="fas fa-user"></i>
                    <%= post.author.userName %> 
                </a>
            </div><hr>
            <h1 class="fw-bold f-size-2-4rem"> <%= post.blogTitle %> </h1>
```

You can use for each loop to display all the items in your js object

2021-04-20 18:39 UTC, Pranav016 commented on routes/index.router.js
> +
Create a new file for testimonial router since later we'll need to add much more backend for testimonial so we should make a new file for it now. Then import it in the index router.

Also update path ` res.render('./postitems/testimonial-write',{` to ` res.render('./posts/testimonial-write',{`

2021-04-21 02:49 UTC, Ankita297 commented on views/partials/footer.ejs
> +<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
need this otherwise the carousel will not work .

2021-04-21 17:11 UTC, Ankita297 commented
@Pranav016  I am busy in my college work . I will make make the changes tomorrow . 
Sorry .

2021-04-21 17:16 UTC, Pranav016 commented
> @Pranav016 I am busy in my college work . I will make make the changes tomorrow .
> Sorry .

👍

2021-04-22 18:37 UTC, Ankita297 commented
@Pranav016  Please see it now .

2021-04-22 21:33 UTC, Pranav016 requested changes
I think the CI pipeline itself reviewed a lot of code so you can refer to that for the changes required

2021-04-22 21:33 UTC, Pranav016 commented on views/partials/testimonial.ejs
> +                                </div>
I suggested using a loop in the first place because the whole point was to reduce the code size but it doesn't seem that way. I have not tested the code on my system but it definitely could be improved since you are importing the data and that makes possible to reduce the size of the code by a lot. I would still like to ask @AnanyaNegi @RushanKhan1 to give reviews and help you out.

2021-04-22 21:33 UTC, Pranav016 commented on testimonial.js
> +const express = require('express');
express not used in this file so you can remove it, that is why it is giving error

2021-04-23 03:13 UTC, Ankita297 commented on views/partials/testimonial.ejs
> +                                </div>
Okay @Pranav016  I will do that .

2021-04-23 03:13 UTC, Ankita297 commented on testimonial.js
> +const express = require('express');
okay i will remove it .

2021-04-26 07:44 UTC, Ankita297 commented
@Pranav016 I will do it today .

2021-04-26 15:20 UTC, Ankita297 commented
@Pranav016  Please  review my PR .

2021-04-26 19:51 UTC, Pranav016 requested changes
* The CI is not passing on this PR since the code is not formatted. 
Use `npm run lint` command before making the commit next time to format the code.

* I did not test it on my system because of less time on hands due to exams.
Can you add a updated demo video of the features added? I'll then be able to clearly see the feature and approve the PR.

* Commit messages are incorrect. I'd advise to squash the commit and add a correct commit message while squashing. 
```
changes updated
testimonial added / updated
```
are less descriptive commit messages and do not follow best practices.

2021-04-26 19:51 UTC, Pranav016 commented on views/partials/testimonial.ejs
> +                </div></div></div></div></div></div></div>
Did not get this

2021-04-26 19:51 UTC, Pranav016 commented on views/partials/testimonial.ejs
> +                            <p class="text-center">Fee free to write ...</p></div>
*Feel free to write

2021-04-26 19:51 UTC, Pranav016 commented on views/partials/testimonial.ejs
> +                            <% for (let i=3; i <testimonial.length; i++ ) { %>
How many testimonials are getting displayed in this carousel slide ?

I checked the loop and there are 3 in the carousel-active slide and the all the other are added in the next slide.
Instead use the loop to make groups of 3 items.  
This loop`let i=3; i <testimonial.length; i++ ` seems incorrect to me.

2021-04-26 19:52 UTC, Pranav016 commented
/level3/

2021-04-27 03:37 UTC, Ankita297 commented on views/partials/testimonial.ejs
> +                            <p class="text-center">Fee free to write ...</p></div>
Sorry type error .

2021-04-27 05:40 UTC, Ankita297 commented
https://user-images.githubusercontent.com/67833077/116190773-d9e3c900-a748-11eb-83bb-f70e1289ec4f.mp4

2021-04-27 05:43 UTC, Pranav016 commented
>  Daily.Journal.-.Google.Chrome.2021-04-27.11-05-38.mp4

neither the heading nor the button should move, only testimonials should move in the carousel

2021-04-27 05:46 UTC, Ankita297 commented
okay @Pranav016

2021-04-27 06:20 UTC, Ankita297 commented
https://user-images.githubusercontent.com/67833077/116194036-e7e81880-a74d-11eb-89e8-203f919b65a5.mp4

2021-04-27 06:56 UTC, Ankita297 commented on views/partials/testimonial.ejs
> +                            <% for (let i=3; i <testimonial.length; i++ ) { %>
@Pranav016  now i have updated the for loop  please see .

2021-04-27 06:57 UTC, Ankita297 commented on views/partials/testimonial.ejs
> +                </div></div></div></div></div></div></div>
I  have corrected it now .

2021-04-27 06:59 UTC, Ankita297 commented
@Pranav016  if you can help me how squash commits ?

2021-04-27 07:06 UTC, Pranav016 commented
> @Pranav016 if you can help me how squash commits ?

https://github.com/ALPHAVIO/ToDoist/pull/6
check a comment on this one..
In this `HEAD~3` just replace `3` with the no of commits you are squashing

2021-04-27 07:37 UTC, Ankita297 commented
![MINGW64__f_BlogSite 27-04-2021 12_47_40](https://user-images.githubusercontent.com/67833077/116203370-3fd84c80-a759-11eb-83bc-251683565887.png)
![MINGW64__f_BlogSite 27-04-2021 12_50_37](https://user-images.githubusercontent.com/67833077/116203383-436bd380-a759-11eb-99cb-eed39dcb3242.png)
@Pranav016  something like this is showing up and also there are  some conflicts in other file .

2021-04-27 07:48 UTC, Pranav016 commented
You should have rebased your branch before squashing, that's what it's saying..

2021-04-27 07:49 UTC, Pranav016 commented
Get your code approved in this branch then make a new PR with that code with 2-3 commits for merging..
Don't worry about squashing rn as soon as your code gets approved

2021-04-27 07:50 UTC, Ankita297 commented
okay @Pranav016

2021-04-27 07:56 UTC, Ankita297 commented
@Pranav016 is it okay now ?

2021-04-27 07:57 UTC, Ankita297 commented
if then can i open another PR ?

2021-04-27 12:06 UTC, Pranav016 approved these changes
Yes you can make a new PR now with these changes and I'll merge
Also use `npm run lint` command before commiting the code

2021-04-27 12:06 UTC, Pranav016 commented on views/partials/footer.ejs
> +<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
Try removing these and test if the carousel still works because I doubt that the scripts are repeated otherwise it's fine 👍

2021-04-27 12:06 UTC, Pranav016 commented on testimonial.js
> +		author: 'John Benson',
Add this file to folder instead of putting it in the root file. Put this in a folder `dummy-data` and update the path where it is used.

2021-04-27 12:06 UTC, Pranav016 commented
closing this PR

2021-04-27 12:06 UTC, closed without merging