Banner added
ALPHAVIO/WordNook pull request #755
Opened 2021-04-26 08:03 UTC by aditisneh

## What is the change?
Banner is added in the readme

## Related issue?
close: #745

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [yes] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [yes] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [yes] Did you lint your code before making the Pull Request?
- [] Have you made corresponding changes to the documentation?
- [] Your submission doesn't break any existing feature.
- [] Have you tested the code before submission?

2021-04-26 08:05 UTC, aditisneh commented
do add proper level tag

2021-04-26 19:58 UTC, Pranav016 requested changes
I think it could be better
![image](https://user-images.githubusercontent.com/54665036/116142205-3e763800-a6f7-11eb-9371-63824c1e0d5a.png)


The one we had previously looks really good, kind of the same format would do the job.

![image](https://user-images.githubusercontent.com/54665036/116142216-446c1900-a6f7-11eb-821b-8f7e1628ef2e.png)


* For this issue I would appreciate if you first get approval in the chat itself if the banner is suitable and then make a PR. That would save your time.
* When it does get approved, remove the previous banner before adding a new banner.
* Add it only to the assets folder, in this PR the banner was added twice.

2021-04-26 19:58 UTC, Pranav016 commented on README.md
> -  <h1>WordNook</h1>
Don't remove this for now.

2021-04-28 12:22 UTC, aditisneh commented
Okay, I understood that. I thought of something else. As you want me to design new banner with previous format, I think first we should work on the logo, so that same logo goes in the banner, right? Thanks for such a good explanation :)

2021-04-29 05:31 UTC, Pranav016 commented
Closing the PR for now, comment on this to reopen PR if required

2021-04-29 05:31 UTC, closed without merging