navigation button added to testimonial
ALPHAVIO/WordNook pull request #795
Opened 2021-05-02 05:25 UTC by Ankita297

## What is the change?
navigation button added to testimonial
## Related issue?
close: #777 

## How was it tested?
I have tested it in my local system 
## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

https://user-images.githubusercontent.com/67833077/116803367-88668000-ab34-11eb-9c38-b001ac4588db.mp4

2021-05-02 05:26 UTC, Ankita297 commented
@Pranav016  Please review my PR .

2021-05-02 05:33 UTC, Pranav016 commented
> @Pranav016 Please review my PR .

The left right buttons work right ?

2021-05-02 05:34 UTC, Ankita297 commented
Yes ,they work .

2021-05-02 05:44 UTC, Pranav016 commented
> And did you check if the feature is responsive for mobile view ?

@Ankita297

2021-05-02 05:54 UTC, Pranav016 requested changes
One change otherwise looks good to merge

2021-05-02 05:54 UTC, Pranav016 commented on views/partials/testimonial.ejs
> +</div>
this code might need some formatting to be done manually, fix the indentations

2021-05-02 11:42 UTC, Ankita297 commented on views/partials/testimonial.ejs
> +</div>
@Pranav016  what is indentations and how can i resolve it ?
and for responsiveness i have check it done bit changes  and it is responsive if you can tell how to  fix the indentations then i will make the commit .

2021-05-02 12:03 UTC, Ankita297 commented
![WordNook - Google Chrome 02-05-2021 17_08_34](https://user-images.githubusercontent.com/67833077/116812414-3c373200-ab6c-11eb-94c7-92e59652efdf.png)

2021-05-02 13:38 UTC, Ankita297 commented
@Pranav016 please see it .

2021-05-02 13:44 UTC, Ankita297 commented
@Pranav016 what about indentations ?

2021-05-02 13:49 UTC, Pranav016 commented on views/partials/testimonial.ejs
> +</div>
With indentation I mean basic code formatting in hierarchy like- (example)
```
<div>
<a href="..">
</div>
```
when correctly indented
```
<div>
    <a href="..">
</div>
``` 
or 
```
                                        <% } %>
                                </div>
                                            <% } %>
                                    </div>
```
this when correctly formatted-
```
                                        <% } %>
                                </div>
                         <% } %>
                  </div>
```

2021-05-02 13:54 UTC, Ankita297 commented on views/partials/testimonial.ejs
> +</div>
Okay

2021-05-02 14:00 UTC, Ankita297 commented
@Pranav016 Please see now .

2021-05-03 07:55 UTC, Pranav016 approved these changes

2021-05-03 07:58 UTC, merged