Adds New Testimonials (Implement Backend for Testimonials)
ALPHAVIO/WordNook pull request #797
Opened 2021-05-02 09:37 UTC by theBeginner86

## What is the change?
- In order for the logged in person to add new testimonials, I created a new ejs file, testimonial-write. This would be rendered onto the testimonial wall page. This will be only visible to the users who have signed in to our website.
- Testimonial-write section take the user's input into the text area and then saves it, as an object of author: full name (of logged in user) and views: entered text. Then it adds this object into the testimonial array which already existed in our project under dummy-data folder. Then this new entered testimonial would be displayed normally like other dummy testimonials.
- Also there would be a button on the top of the testimonial wall page which takes the user to the section which contains the testimonial-write area. This button would only be visible to the logged in user.

## Related issue?
close: #792

## How was it tested?
Tested Locally

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [] Have you made corresponding changes to the documentation?
- [] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
<img width="1440" alt="Screenshot 2021-05-02 at 2 15 49 PM" src="https://user-images.githubusercontent.com/73700530/116807559-721aed00-ab51-11eb-852e-775d6c05c1fa.png">

<img width="1440" alt="Screenshot 2021-05-02 at 2 16 10 PM" src="https://user-images.githubusercontent.com/73700530/116807522-33853280-ab51-11eb-8580-8ce271243ec4.png">

For video (google drive link):
https://drive.google.com/drive/folders/16-STi72QCWY1PdNcQzOV06VHCKv1ulVp?usp=sharing

2021-05-02 13:36 UTC, Pranav016 requested changes

2021-05-02 13:36 UTC, Pranav016 commented on views/testimonials/testimonial-wall.ejs
> +            <button class="btn btn-primary block add-new-testimonial">Add New Testimonials</button>
You can reuse the `button` class to style your buttons to match the buttons on the rest of the website and remove the class that you have added to style it

2021-05-02 13:37 UTC, Pranav016 commented
Also use command `npm run lint` before your next commit

2021-05-02 13:38 UTC, theBeginner86 commented on views/testimonials/testimonial-wall.ejs
> +            <button class="btn btn-primary block add-new-testimonial">Add New Testimonials</button>
ok I will do that.

2021-05-02 13:38 UTC, Pranav016 commented
/gssoc/

2021-05-02 13:38 UTC, Pranav016 commented
/level3/

2021-05-02 13:39 UTC, theBeginner86 commented
ok I will try to do that all those things.

2021-05-03 07:54 UTC, Pranav016 requested changes

2021-05-03 07:54 UTC, Pranav016 commented on public/css/styles.css
> +
Since you are reusing the `button` class hence I think you can remove this unwanted css and remove these classes from the components as well

2021-05-03 08:01 UTC, theBeginner86 commented on public/css/styles.css
> +
No actually I used them because there was some unwanted behaviour if I do not use them. The button class which is already there have some extra space for the icon. So if I do not use these then with the text inside the button exists with some extra blank space with white background for the icon which we our using on the home page. But since I think we do not require the icon testimonial wall so I tried to add another class to improve it. 
But still if you want me to remove that then I will do it. Or shall I send here the screenshot of how the page looks if I use just the button class.

2021-05-03 08:12 UTC, Pranav016 commented on public/css/styles.css
> +
Add a suitable icon in the button, use the class for the pen icon.
And yes you can remove these classes..

2021-05-03 08:15 UTC, theBeginner86 commented on public/css/styles.css
> +
ok I will do it just now.

2021-05-03 08:18 UTC, theBeginner86 commented on public/css/styles.css
> +
One more doubt, if I have to position the buttons to the place where I have placed them right now, so should I use inline css for that or if you have any suggestions then please tell me.

2021-05-03 08:39 UTC, Pranav016 commented on public/css/styles.css
> +
New class

2021-05-03 08:44 UTC, theBeginner86 commented on public/css/styles.css
> +
I did not understand. What is / create a new class?
Can you please tell.

2021-05-03 08:48 UTC, Pranav016 commented on public/css/styles.css
> +
> I did not understand. What is / create a new class?
> Can you please tell.

My bad, I meant you can make a separate class for positioning

2021-05-03 08:49 UTC, theBeginner86 commented on public/css/styles.css
> +
Now understood. I will do it just now.

2021-05-03 11:18 UTC, Pranav016 approved these changes

2021-05-03 11:19 UTC, merged

2021-05-26 11:58 UTC, RushanKhan1 commented
@all-contributors please add @theBeginner86  for code