alignment of content in footer
ALPHAVIO/WordNook pull request #803
Opened 2021-05-03 04:40 UTC by Ankita297

## What is the change?
alignment of content in footer
## Related issue?
close: #522 

## How was it tested?
I have tested it in my local system .
## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.
![WordNook - Google Chrome 03-05-2021 10_05_58](https://user-images.githubusercontent.com/67833077/116841752-bd87d680-abf7-11eb-9f45-e9ef00ce69d1.png)

2021-05-03 04:41 UTC, Ankita297 commented
@Pranav016 Please review my PR .

2021-05-03 07:51 UTC, Pranav016 requested changes

2021-05-03 07:51 UTC, Pranav016 commented on views/partials/footer.ejs
> +      <ul class="list-unstyled mb-0 mx-0" >
did you check if there is margin applied to this in the css file ?
You can just remove that or remove `mb-0` and `mx-0` from here apply `margin: 0px` directly to in the css file.

This solution that you did also works but if you can find a better solution to keep the code clean then it would be great.

2021-05-03 12:40 UTC, Ankita297 commented
@Pranav016 Please see now .

2021-05-03 13:29 UTC, Pranav016 approved these changes

2021-05-03 13:29 UTC, merged

2021-05-03 13:29 UTC, Pranav016 commented
/gssoc/

2021-05-03 13:29 UTC, Pranav016 commented
/level2/

2021-05-15 09:30 UTC, Pranav016 reviewed
Make a PR for this change

2021-05-15 09:30 UTC, Pranav016 commented on public/css/styles.css
>  }
remove these properties if the margin is 0px