added responsiveness to the site
ALPHAVIO/WordNook pull request #821
Opened 2021-05-05 19:53 UTC by ritik307

## What is the change?
Added responsiveness to the mobile and tablet view of the website

## Related issue?
close: #739 

## How was it tested?
1. Click F12
2.  Change the mode to mobile or tablet.
3. The website will NOT have an unnecessary margin on the left side and the content of the website will NOT look distorted.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:

https://user-images.githubusercontent.com/22374829/117200760-7a04b680-ae09-11eb-86b7-830d42ccce12.mp4

2021-05-05 19:53 UTC, ritik307 commented
@AnanyaNegi @Pranav016 Plz review

2021-05-06 16:42 UTC, Pranav016 requested changes

2021-05-06 16:42 UTC, Pranav016 commented on public/css/styles.css
> +	/* margin: 0.8rem; */
remove this line of code

2021-05-06 16:42 UTC, Pranav016 commented on views/partials/header.ejs
> +      <nav id="nav-id" class="navbar navbar-expand-lg navbar-default darkmode--activated sticky-top">
shouldn't the nav be in the header instead of body

2021-05-06 16:47 UTC, ritik307 commented on views/partials/header.ejs
> +      <nav id="nav-id" class="navbar navbar-expand-lg navbar-default darkmode--activated sticky-top">
I don't think so by the convention _The head element contains metadata—information that describes the document itself or associates it with related resources, such as scripts and style sheets. and the rest should belong to the body._

[Reference Link](https://stackoverflow.com/questions/31768460/should-i-place-my-navbar-before-or-after-the-body-tag-when-customizing-a-wp)

2021-05-09 12:06 UTC, merged

2021-05-09 12:09 UTC, ritik307 commented
@Pranav016 The issue is of level 3 and you have added a wrong level tag plz fix it.