social icons are enhanced
ALPHAVIO/WordNook pull request #836
Opened 2021-05-08 13:35 UTC by Ankita297

## What is the change?
social icons are enhanced 
## Related issue?
close: #820 

## How was it tested?
I have tested it in my local system 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.

https://user-images.githubusercontent.com/67833077/117541062-bd406e80-b02f-11eb-9c13-a384b6276935.mp4

![Gurujii com - Google Chrome 08-05-2021 18_56_40](https://user-images.githubusercontent.com/67833077/117541138-17d9ca80-b030-11eb-8733-4f58cd08a864.png)

2021-05-08 13:35 UTC, Ankita297 commented
@Pranav016 Please review my PR .

2021-05-08 13:44 UTC, Pranav016 commented
> @Pranav016 Please review my PR .

Please don't tag unless it's very urgent or it's been more than 36hrs since PRs been made.

2021-05-08 13:54 UTC, Ankita297 commented
Sorry Sir  . I will not repeat it .

2021-05-08 18:22 UTC, Pranav016 requested changes
In the mobile view screenshot you added, there is a horizontal scroll bar visible which shouldn't be there.
I think it because the size of the icons is not shrinking for mobile view, even in mobile view they look big. I'd suggest that for their size instead of rem use `vw` unit and also for font size where `px` unit was used to set it.

2021-05-09 04:07 UTC, Ankita297 commented
![WordNook - Google Chrome 09-05-2021 09_36_54](https://user-images.githubusercontent.com/67833077/117560288-2795f500-b0aa-11eb-989c-47cfa7f47238.png)

2021-05-09 12:02 UTC, Pranav016 requested changes
There is a lot of unnecessary css used like the media queries etc which is cluttering the code and that could be avoided just by using the correct units. Don't stick to `rem` for all the values, use `vw` or `vh` wherever you could use it.
Writing clean css would also avoid the used of - `overflow-x: hidden;` here

2021-05-09 12:02 UTC, Pranav016 commented on public/css/styles.css
> +		font-size: 20px;
size is hard coded, instead remove this media query and set a relative size to it in the first place itself.

2021-05-09 13:04 UTC, Ankita297 commented
The horizontal bar was already present there even before i have added the code  so  i just add the code overflow-x:hidden in body So i don't think it is due to footer  . So what should i do in this ?  
![WordNook - Google Chrome 09-05-2021 18_06_33](https://user-images.githubusercontent.com/67833077/117572642-68fdc300-b0f1-11eb-823a-63e1fbd39775.png)

2021-05-09 13:51 UTC, Pranav016 commented
> The horizontal bar was already present there even before i have added the code so i just add the code overflow-x:hidden in body So i don't think it is due to footer . So what should i do in this ?
> ![WordNook - Google Chrome 09-05-2021 18_06_33](https://user-images.githubusercontent.com/67833077/117572642-68fdc300-b0f1-11eb-823a-63e1fbd39775.png)

Ok so just remove the overflow-x and improve the overall css you added because that still has some issues. I'll take care of the horizontal scroll.

2021-05-09 14:47 UTC, Ankita297 commented on public/css/styles.css
> +		font-size: 20px;
I have remove all the media query  and replace it with % .

2021-05-10 13:20 UTC, Ankita297 commented
changes done Please check .

2021-05-10 14:17 UTC, Pranav016 approved these changes

2021-05-10 14:18 UTC, merged

2021-05-10 14:27 UTC, Ankita297 commented
Thank You Sir