Added wall button on home page
ALPHAVIO/WordNook pull request #841
Opened 2021-05-09 16:39 UTC by satcasm

Fixes: #812 

Screenshot:
![image](https://user-images.githubusercontent.com/56315878/117579980-2e0c8700-b113-11eb-9d0f-4c38adbf0b29.png)

2021-05-09 22:30 UTC, Pranav016 commented
How does it look in mobile view ?

2021-05-09 22:37 UTC, Pranav016 requested changes

2021-05-09 22:37 UTC, Pranav016 commented on public/css/styles.css
> +
you don't need to add all the styles again, just reuse the `button` and `arrow` class for adding the styles.
Add this class only for positioning the button.

2021-05-10 09:28 UTC, satcasm commented
> How does it look in mobile view ?

The responsiveness of the site is pretty messed up before ```900pxs```.
![blog1](https://user-images.githubusercontent.com/56315878/117637800-c9e3d480-b19f-11eb-9306-70e994846b00.gif)

2021-05-10 13:54 UTC, Pranav016 commented
> > How does it look in mobile view ?
> 
> The responsiveness of the site is pretty messed up before `900pxs`.
> ![blog1](https://user-images.githubusercontent.com/56315878/117637800-c9e3d480-b19f-11eb-9306-70e994846b00.gif)

I checked on my system, the website looks fine in mobile view, the issue is only for tablet view.

2021-05-10 13:58 UTC, Pranav016 requested changes
I saw the demo video and I think we shouldn't have the testimonial wall button at the top in mobile view. I think we should put it below the `hello there` h1 so that in mobile view it comes under that heading.


I would like to hear your suggestions as well regarding the positioning of the button

2021-05-10 14:53 UTC, satcasm commented
Let me try with that look and will let you know how that looks.

2021-05-13 06:26 UTC, satcasm commented
So @Pranav016 , should I go with this or not?

2021-05-13 13:41 UTC, Pranav016 commented
Yes for now we can do this, maybe in the future I'll come up with a better position for the button. You can push your code now 👍

2021-05-13 18:16 UTC, satcasm commented
@Pranav016 pushed the changes have a look.
Thanks!

2021-05-14 19:42 UTC, Pranav016 approved these changes

2021-05-14 19:43 UTC, merged

2021-05-26 12:03 UTC, RushanKhan1 commented
@all-contributors please add @satcasm for code