contact form updated
ALPHAVIO/WordNook pull request #856
Opened 2021-05-12 07:46 UTC by Ankita297

## What is the change?
contact form updated
## Related issue?
close: #838 

## How was it tested?
I have tested it in my local system .
## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.
![WordNook - Google Chrome 12-05-2021 12_14_52](https://user-images.githubusercontent.com/67833077/117937560-c6795600-b323-11eb-9840-6ca374ad60bc.png)
![WordNook - Google Chrome 12-05-2021 13_04_42](https://user-images.githubusercontent.com/67833077/117938019-38ea3600-b324-11eb-9fd4-021c6beb5343.png)
![WordNook - Google Chrome 12-05-2021 13_04_34](https://user-images.githubusercontent.com/67833077/117937634-d7c26280-b323-11eb-8dc5-210fef816a23.png)
![WordNook - Google Chrome 12-05-2021 13_04_42](https://user-images.githubusercontent.com/67833077/117937730-f0327d00-b323-11eb-889a-e55e2188b867.png)
![WordNook - Google Chrome 12-05-2021 13_04_53](https://user-images.githubusercontent.com/67833077/117937793-fde80280-b323-11eb-8e9b-f88e2ba66b76.png)

2021-05-12 08:30 UTC, Pranav016 requested changes
Good work,
![image](https://user-images.githubusercontent.com/54665036/117943938-46a2ba00-b32a-11eb-84cf-9b1926da7be8.png)

This blue bar at the top looks weird and you can remove it. Add a bit more border radius to the whole form area and PR will be good to merge 👍 

Also run `npm run lint` before your next commit.

2021-05-12 08:30 UTC, Pranav016 commented on public/css/styles.css
> +	width: 650px;
I would suggest refrain from using `px` to set width, use `vw`

2021-05-12 09:08 UTC, Ankita297 commented on public/css/styles.css
> +	width: 650px;
Sir i have done the changes where i can and i have tested it . and npm run lint is failing due to first commit . 
Sorry for that i will keep that in mind from next time .

2021-05-12 09:08 UTC, Ankita297 commented
Sir done the changes 

![WordNook - Google Chrome 12-05-2021 14_23_32](https://user-images.githubusercontent.com/67833077/117949074-612b6200-b32f-11eb-8f25-1509ee1c1706.png)
![WordNook - Google Chrome 12-05-2021 14_23_08](https://user-images.githubusercontent.com/67833077/117948904-37723b00-b32f-11eb-854c-ae23733a9430.png)

2021-05-12 12:34 UTC, Pranav016 approved these changes

2021-05-12 12:35 UTC, merged

2021-05-12 13:39 UTC, Ankita297 commented
Thankyou sir

2021-05-15 09:26 UTC, Pranav016 reviewed
Make these changes as well to clean the code

2021-05-15 09:26 UTC, Pranav016 commented on views/navitems/contact.ejs
> +        <button class="btn btn-primary  send-btn" type="submit">Send</button>
remove the `btn` `btn-primary` class from this and reuse the button class there in the styles.css
and then add the extra css to this send-btn class. Add all the colors and hover again to this class doesn't make sense.
btn-primary should also be removed, no point of having it

2021-05-15 09:26 UTC, Pranav016 commented on views/navitems/contact.ejs
> +              <textarea class="form-control col-md-12 col-sm-12 col-xs-12" rows="6" name="message" placeholder="Your Message" value="<%= formData.message %>" required></textarea>
use col-12 class instead of all of these

2021-05-15 09:26 UTC, Pranav016 commented on views/navitems/contact.ejs
> +              <textarea class="form-control col-md-12 col-sm-12 col-xs-12" rows="6" name="message" placeholder="Your Message" value="<%= formData.message %>" required></textarea>
col-12

2021-05-15 09:29 UTC, Ankita297 commented on views/navitems/contact.ejs
> +              <textarea class="form-control col-md-12 col-sm-12 col-xs-12" rows="6" name="message" placeholder="Your Message" value="<%= formData.message %>" required></textarea>
okay Sir

2021-05-15 09:53 UTC, Ankita297 commented
![profile page enhanced by Ankita297 · Pull Request #883 · ALPHAVIO_WordNook - Google Chrome 15-05-2021 15_22_07](https://user-images.githubusercontent.com/67833077/118356124-6b4c9b00-b591-11eb-8a73-8731b144d38c.png)
is this okay ?

2021-05-15 10:54 UTC, Pranav016 commented
Make PR or whatever changes I had requested, I'll review them then..