Styled text on profile page
ALPHAVIO/WordNook pull request #869
Opened 2021-05-13 15:01 UTC by tanishq-arya

## What is the change?
added outline text class with text shadow

## Related issue?
close: #717 

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [] Did you lint your code before making the Pull Request?
- [] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
![image](https://user-images.githubusercontent.com/77333275/118144556-36720400-b42a-11eb-8b10-52b5215e2f6b.png)

2021-05-13 16:43 UTC, Pranav016 commented
Text of the whole website needs to be updated. Not just one page

2021-05-14 06:55 UTC, tanishq-arya commented
> Text of the whole website needs to be updated. Not just one page

@Pranav016 I think that would look a bit weird. I can implement that but I think what we can do is choose a darker color as the primary color. Let me know if I should go forward with the white one only.

2021-05-14 19:53 UTC, Pranav016 requested changes
Add this text-shadow to all the text on the website, don't make a separate class for this and then add it to all the text on the website, instead try to look for other ways to do this like selecting all the h1 tags or p tags etc and giving them text-shadow.

2021-05-14 19:53 UTC, Pranav016 commented on public/css/styles.css
> +	text-shadow: -1px -1px 0px #fff, 1px -1px 0px #fff, -1px 1px 0px #fff, 1px 1px 0px #fff;
just have `text-shadow: 1px 1px 0px white` or `text-shadow: 1px 1px 1px white`, because the one that you've added here gives it a bit more dense look. We just need some white outline for visibility.

A little font-weight can also be added if it looks good to you with this shadow.  `text-shadow: 1px 1px 1px white`

2021-05-17 06:28 UTC, tanishq-arya commented on public/css/styles.css
> +	text-shadow: -1px -1px 0px #fff, 1px -1px 0px #fff, -1px 1px 0px #fff, 1px 1px 0px #fff;
Okay, I'll update it.

2021-05-21 05:42 UTC, tanishq-arya commented
![image](https://user-images.githubusercontent.com/77333275/119087650-18f1fb00-ba25-11eb-9b2f-aed6610e0eec.png)
![image](https://user-images.githubusercontent.com/77333275/119087720-3757f680-ba25-11eb-9204-c2be39cc92f4.png)
![image](https://user-images.githubusercontent.com/77333275/119087839-62424a80-ba25-11eb-902c-1a3cd3cb198a.png)

2021-05-21 15:20 UTC, Pranav016 commented
Yup, these look good 👍

2021-05-21 15:20 UTC, Pranav016 approved these changes

2021-05-21 15:20 UTC, merged