responsiveness of carousel
ALPHAVIO/WordNook pull request #871
Opened 2021-05-13 15:46 UTC by Ankita297

## What is the change?
responsiveness of carousel
## Related issue?
close: #864 

## How was it tested?
I have tested it in my local system 
## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
Add a screenshot or demo video if appropriate.
![WordNook - Google Chrome 13-05-2021 21_03_20](https://user-images.githubusercontent.com/67833077/118150573-55739480-b430-11eb-8c81-2461656a97ec.png)
![WordNook - Google Chrome 13-05-2021 21_09_52](https://user-images.githubusercontent.com/67833077/118150579-56a4c180-b430-11eb-8db1-78eaa0d79bb3.png)

2021-05-13 15:49 UTC, Ankita297 commented
![MINGW64__f_BlogSite 13-05-2021 21_17_26](https://user-images.githubusercontent.com/67833077/118150914-b3a07780-b430-11eb-89fa-6746e54f2df8.png)
Sir i have run npm run lint but still ci checks are failing

2021-05-13 16:38 UTC, Pranav016 requested changes

2021-05-13 16:38 UTC, Pranav016 commented on public/css/styles.css
> +	margin-bottom: 34px;
can you add a bootstrap class like `mb-3` (value accordingly) to the items for margin bottom or make this value in rem.

2021-05-13 16:42 UTC, Ankita297 commented on public/css/styles.css
> +	margin-bottom: 34px;
I will make them in rem

2021-05-13 16:55 UTC, Ankita297 commented
done the changes

2021-05-14 19:53 UTC, Pranav016 approved these changes

2021-05-14 19:53 UTC, merged