profile page enhanced
ALPHAVIO/WordNook pull request #883
Opened 2021-05-15 05:47 UTC by Ankita297

## What is the change?
profile page updated
## Related issue?
close: #861 

## How was it tested?
I have tested it in my local system
## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots
![WordNook - Google Chrome 15-05-2021 10_37_09](https://user-images.githubusercontent.com/67833077/118349563-041def00-b56f-11eb-9713-d799f2e7b769.png)
![WordNook - Google Chrome 15-05-2021 10_37_13](https://user-images.githubusercontent.com/67833077/118349567-0a13d000-b56f-11eb-86c0-6f435696be1e.png)

 or Video:
Add a screenshot or demo video if appropriate.
![WordNook - Google Chrome 15-05-2021 10_36_09](https://user-images.githubusercontent.com/67833077/118349519-cae57f00-b56e-11eb-9dfe-a0919f93592d.png)
![WordNook - Google Chrome 15-05-2021 10_36_20](https://user-images.githubusercontent.com/67833077/118349525-d2a52380-b56e-11eb-9bd4-c288d837f337.png)

2021-05-15 09:07 UTC, Pranav016 commented
![image](https://user-images.githubusercontent.com/54665036/118354919-fd9d7080-b58a-11eb-9191-49241d296d8e.png)
 these buttons would look good center aligned

2021-05-15 09:18 UTC, Ankita297 commented
![WordNook - Google Chrome 15-05-2021 14_47_18](https://user-images.githubusercontent.com/67833077/118355222-879a0900-b58c-11eb-8e89-683e5c533930.png)
![WordNook - Google Chrome 15-05-2021 14_47_28](https://user-images.githubusercontent.com/67833077/118355229-8ec11700-b58c-11eb-84e0-534ab24e9861.png)
is this okay ?

2021-05-15 09:19 UTC, Pranav016 requested changes
I didn't review your previous PR this carefully, don't know how many mistakes were there in those

2021-05-15 09:19 UTC, Pranav016 commented on public/css/styles.css
> +	padding-left: 0%;
write clean css, these 4 lines can be replaced with a single line, `padding: 5% 0;` 

Example- 
```
padding: 25px 50px;
top and bottom paddings are 25px
right and left paddings are 50px
```

2021-05-15 09:19 UTC, Pranav016 commented on views/useritems/read-profile.ejs
> +    <h1 class="heading-centre heading-bold normal-heading-font">Edit Profile</h1>
Is `container-centre` or `heading-centre` or `heading-bold` even a valid bootstrap class ?

2021-05-15 09:19 UTC, Pranav016 commented on views/useritems/read-profile.ejs
> +                        <div class="col-md-12 col-sm-12 col-xs-12">
very bad bootstrap and css, instead of these 3 classes you could just use one class `col-12`

2021-05-15 09:19 UTC, Pranav016 commented on views/useritems/read-profile.ejs
> +                        <div class="col-md-12 col-sm-12 col-xs-12">
`col-12`

2021-05-15 09:23 UTC, Ankita297 commented on public/css/styles.css
> +	padding-left: 0%;
I will correct it

2021-05-15 09:25 UTC, Ankita297 commented on views/useritems/read-profile.ejs
> +    <h1 class="heading-centre heading-bold normal-heading-font">Edit Profile</h1>
these classes are already define in style.css . These are already used in compose page so i have copy it from there

2021-05-15 09:32 UTC, Ankita297 commented on views/useritems/read-profile.ejs
> +                        <div class="col-md-12 col-sm-12 col-xs-12">
okay Sir

2021-05-15 09:37 UTC, Ankita297 commented
done the changes

2021-05-16 01:37 UTC, Pranav016 approved these changes

2021-05-16 01:37 UTC, merged