Logo Changed
ALPHAVIO/WordNook pull request #903
Opened 2021-05-20 15:05 UTC by aanchalrakheja

## What is the change?
Created a new logo for the website

## Related issue?
close: #746 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
![image](https://user-images.githubusercontent.com/68388581/119002697-b9570980-b9aa-11eb-9f03-f5ba8dc5aa20.png)
![image](https://user-images.githubusercontent.com/68388581/119002809-ce339d00-b9aa-11eb-8ab2-ef07ca077ae5.png)
![image](https://user-images.githubusercontent.com/68388581/119002850-dab7f580-b9aa-11eb-8062-28ad0d514f7e.png)

2021-05-20 17:29 UTC, RushanKhan1 requested changes

2021-05-20 17:29 UTC, RushanKhan1 commented on public/css/styles.css
> +	max-width:25rem; */
Please remove the unnecessary comments. Else everything looks good to me. 👍🏻

2021-05-21 13:07 UTC, aanchalrakheja commented on public/css/styles.css
> +	max-width:25rem; */
okay

2021-05-21 13:47 UTC, aanchalrakheja commented
Please check once

2021-05-21 15:25 UTC, merged

2021-05-21 16:57 UTC, Pranav016 commented
@aanchalrakheja the logo looks really good on the website, thanks!