Solved issue with Box-Shadow in Nav-toggler
ALPHAVIO/WordNook pull request #946
Opened 2021-05-26 18:08 UTC by AshuKV

## What is the change?

Redesigned Box-Shadow in Nav-toggler

## Related issue?
close: #879 

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
 
![image](https://user-images.githubusercontent.com/48694961/119709985-78b03200-be7b-11eb-976a-536b6b12d602.png)

2021-05-26 19:15 UTC, Pranav016 requested changes
There are changes done to the package-lock file which are not required. Revert those changes.
Check README for instructions for package-lock file version 2 to avoid these changes in the future.

2021-05-26 19:15 UTC, Pranav016 commented on public/css/styles.css
> +	opacity: 0.1;
Opacity is making the toggler button look very light (in the screenshot you added).

It looked pretty decent before
![image](https://user-images.githubusercontent.com/54665036/119718037-b6fe1f00-be84-11eb-99b9-5ec7f4ccc83d.png)

i think adding only the box-shadow would do the job

2021-05-29 18:54 UTC, AshuKV reviewed
Can you please suggest me what changes I have to do in package-lock.json file.

2021-05-30 18:44 UTC, Pranav016 commented
> Can you please suggest me what changes I have to do in package-lock.json file.

You have to revert the changes you did in package-lock file.

2021-05-31 17:18 UTC, AshuKV commented
The conflicts have been resolved. Finally you could merge the PR now. Thanks for the help.

2021-05-31 17:36 UTC, Pranav016 commented
> The conflicts have been resolved. Finally you could merge the PR now. Thanks for the help.

There are still changes to the package-lock file which should be reverted.

2021-05-31 17:37 UTC, Pranav016 commented
You can take help from this https://stackoverflow.com/questions/215718/how-can-i-reset-or-revert-a-file-to-a-specific-revision

2021-05-31 20:27 UTC, Pranav016 approved these changes

2021-05-31 20:28 UTC, merged