Added captcha in singUp form
ALPHAVIO/WordNook pull request #947
Opened 2021-05-27 18:17 UTC by satcasm

Fixes: #642 
Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/119876748-d90ba600-bf45-11eb-813d-053c2ba939b3.png)

2021-05-28 16:09 UTC, Pranav016 requested changes
Lint the code before committing

2021-05-28 16:09 UTC, Pranav016 commented on routes/user.router.js
> +		const secretKey = '6LecnfAaAAAAAC2AOAYwA2xyHLbiuPqkdJHDHwYX';
shouldn't this secret key stored as an env variable ?

2021-05-29 05:14 UTC, satcasm commented on routes/user.router.js
> +		const secretKey = '6LecnfAaAAAAAC2AOAYwA2xyHLbiuPqkdJHDHwYX';
I thought you would be generating a new key as I wasn't sure which domains to give access to, that's why I didn't make it an env variable. 
Kindly go through this: https://www.google.com/recaptcha/admin/create.
Also, select this option:
![image](https://user-images.githubusercontent.com/56315878/120058787-d3f44700-c06a-11eb-9713-8de8e584942a.png)
Apologies for inconvenience.

2021-05-29 15:52 UTC, satcasm commented on routes/user.router.js
> +		const secretKey = '6LecnfAaAAAAAC2AOAYwA2xyHLbiuPqkdJHDHwYX';
Or I can add word-nook.herokuapp.com/ as a domain and make the secret key as env, whichever works for you.
Let me know.

2021-05-30 16:31 UTC, satcasm commented
@Pranav016 any update on this?

2021-05-30 18:49 UTC, Pranav016 commented on routes/user.router.js
> +		const secretKey = '6LecnfAaAAAAAC2AOAYwA2xyHLbiuPqkdJHDHwYX';
Sorry for the late reply, yes you can use ALPHAVIO's account to set the domain and make the secret key as an env. You can get ALPHAVIO's account credentials from me on discord

2021-05-31 13:42 UTC, Pranav016 commented
> > @Pranav016 any update on this?

> Sorry for the late reply, yes you can use ALPHAVIO's account to set the domain and make the secret key as an env. You can get ALPHAVIO's account credentials from me on discord

yes

2021-05-31 17:39 UTC, Pranav016 commented
Make the secret as an env variable and resolve conflicts to get it merged

2021-06-02 13:23 UTC, Pranav016 approved these changes

2021-06-02 13:23 UTC, merged