Added styles to the newletter btn and made the div responsive
ALPHAVIO/WordNook pull request #998
Opened 2021-06-07 16:21 UTC by yashraj-02-techie

## What is the change?
Added styles to the newletter signup button to match it with the other button used throughout the website. Made the newsletter sign up div responsive.

## Related issue?
close: #988 

## How was it tested?
The code was tested on the local machine. Checked the responsiveness using the device toggle option for various devices.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

- [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/BlogSite/pulls) for the same update/change?
- [x] Did you lint your code before making the Pull Request?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you tested the code before submission?

## Screenshots or Video:
![image](https://user-images.githubusercontent.com/76647423/121055040-8c905800-c7da-11eb-9639-b95ec46a0c7a.png)

2021-06-07 20:21 UTC, theBeginner86 commented
@yashraj-02-techie 
Nice efforts! 
- But I wanted to ask that did you properly run: npm install, before making the changes. I feel that there are some variations due to that and are causing some changes in the package-lock.json. Which might cause serious issues on merging.
Try to fix that.
- Also, if you could decrease the extra space on either side of the newsletter div then that would further make it look much cleaner.

<img width="1434" alt="Screenshot 2021-06-08 at 1 26 25 AM" src="https://user-images.githubusercontent.com/73700530/121080676-58785f80-c7f9-11eb-94c2-3ff69389c934.png">


Let me know how that sounds.

2021-06-07 22:46 UTC, Pranav016 requested changes
- Changes have been made to package-lock file which are not appreciated, check the README.md for instructions on lock file version 2. Please revert these changes.
- Make PR from a new branch

2021-06-07 22:46 UTC, Pranav016 commented on views/useritems/newsletter.ejs
> +                <button class="btnFrame" style= " font-size: 18px; font-weight: 500;"  type="submit">Click Here to subscribe our newsletter</button>
We absolutely discourage any inline css because its not a good practice and encourage using previously made classes. I know there was some inline css there from before in this component but you can start from fresh and add styling to the css file. I think you can reuse the class given to the form above this, this will help maintain same size as the form, make it responsive and add background shadow without any hassle. You could also reuse button classes.

2021-06-07 22:48 UTC, Pranav016 commented
> @yashraj-02-techie
> Nice efforts!
> 
> * I wanted to ask that did you properly run: npm install, before making the changes. I feel that there are some variations due to that and are causing some changes in the package-lock.json. Which might cause serious issues on merging.
>   Try to fix that.
> * Also, if you could decrease the extra space on either side of the newsletter div then that would further make it look much cleaner.
> 
> <img alt="Screenshot 2021-06-08 at 1 26 25 AM" width="1434" src="https://user-images.githubusercontent.com/73700530/121080676-58785f80-c7f9-11eb-94c2-3ff69389c934.png">

great suggestions, if @yashraj-02-techie uses the form class then he won't need to worry about the extra space on the side since it would be responsive and will get the same styling 👍

2021-06-08 16:09 UTC, yashraj-02-techie commented on views/useritems/newsletter.ejs
> +                <button class="btnFrame" style= " font-size: 18px; font-weight: 500;"  type="submit">Click Here to subscribe our newsletter</button>
Hey I realize that its a bad practice but as you said there was inline css before. Anyways I'll make sure I add classes to it and remove the inline css.

2021-06-08 16:33 UTC, closed without merging